### ISSUE TITLE
Unable to compile custom function

### ISSUE THREAD

**Issue by csreddyennam** [OfficeDev/Excel-Custom-Functions#276]
I am able to build locally, but issue is on my build machine.

Command used to compile: webpack -p --mode production --https false
 
Error Message:
2021-05-14T15:23:23.3202801Z   > webpack -p --mode production --https false
2021-05-14T15:23:23.3203373Z   
2021-05-14T15:23:24.7986037Z   (node:7096) UnhandledPromiseRejectionWarning: TypeError: The 'compilation' argument must be an instance of Compilation
2021-05-14T15:23:24.7986768Z       at Function.getCompilationHooks (d:\xxx\s\src\Common\wwwroot\InSight\excelAddin\node_modules\custom-functions-metadata-plugin\node_modules\webpack\lib\NormalModule.js:195:10)
2021-05-14T15:23:24.7987515Z       at compiler.hooks.compilation.tap (d:\xxx\s\src\Common\wwwroot\InSight\excelAddin\node_modules\custom-functions-metadata-plugin\lib\customfunctionsplugin.js:41:36)
2021-05-14T15:23:24.7989821Z       at SyncHook.eval [as call] (eval at create (d:\xxx\s\src\Common\wwwroot\InSight\excelAddin\node_modules\tapable\lib\HookCodeFactory.js:19:10), <anonymous>:11:1)
2021-05-14T15:23:24.7990618Z       at SyncHook.lazyCompileHook (d:\XXX\s\src\Common\wwwroot\InSight\excelAddin\node_modules\tapable\lib\Hook.js:154:20)
2021-05-14T15:23:24.7991182Z       at Compiler.newCompilation (d:\xxx\s\src\Common\wwwroot\InSight\excelAddin\node_modules\webpack\lib\Compiler.js:631:26)
2021-05-14T15:23:24.7991788Z       at hooks.beforeCompile.callAsync.err (d:\ADOBuild1\16\s\src\Common\wwwroot\InSight\excelAddin\node_modules\webpack\lib\Compiler.js:667:29)
2021-05-14T15:23:24.7992414Z       at _promise0.then._result0 (eval at create (d:\ADOBuild1\16\s\src\Common\wwwroot\InSight\excelAddin\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:13:1)
2021-05-14T15:23:24.7992940Z       at process._tickCallback (internal/process/next_tick.js:68:7)
2021-05-14T15:23:24.7993245Z       at Function.Module.runMain (internal/modules/cjs/loader.js:834:11)
2021-05-14T15:23:24.7993557Z       at startup (internal/bootstrap/node.js:283:19)
2021-05-14T15:23:24.7993832Z       at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)
2021-05-14T15:23:24.7994429Z   (node:7096) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
2021-05-14T15:23:24.7995258Z   (node:7096) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
2021-05-14T15:23:24.8792850Z   File not found - dist
2021-05-14T15:23:24.8793183Z   0 File(s) copied

**Comment by grangeryy** [comment]
@csreddyennam  Based on our investigation, if you can build locally successfully, usually it indicates there's no issue with the Custom Functions. I'm guessing the problem happens with the build machine itself. Have you ever tried another machine?
