### ISSUE TITLE
TypeError: The 'compilation' argument must be an instance of Compilation

### ISSUE THREAD

**Issue by BrendyRyan** [OfficeDev/Excel-Custom-Functions#300]
When running `npm start` it results in this error. I used the Yo Office generator. Seems to be an error with webpack? Not sure tbh. Any ideas? I am on the recommended versions of npm and node. Didn't change any of the files at all.

```
C:\Users\DELL\documents\coding\office-js-api\Excel-Custom-Functions-master\node_modules\webpack\lib\NormalModule.js:203
                        throw new TypeError(
                              ^

TypeError: The 'compilation' argument must be an instance of Compilation
    at Function.getCompilationHooks (C:\Users\DELL\documents\coding\office-js-api\Excel-Custom-Functions-master\node_modules\webpack\lib\NormalModule.js:203:10)
    at C:\Users\DELL\documents\coding\office-js-api\Excel-Custom-Functions-master\node_modules\custom-functions-metadata-plugin\lib\customfunctionsplugin.js:55:36
    at Hook.eval [as call] (eval at create (C:\Users\DELL\Documents\Coding\office-js-api\Excel-Custom-Functions-master\node_modules\tapable\lib\HookCodeFactory.js:19:10), <anonymous>:100:1)
    at Hook.CALL_DELEGATE [as _call] (C:\Users\DELL\Documents\Coding\office-js-api\Excel-Custom-Functions-master\node_modules\tapable\lib\Hook.js:14:14)
    at Compiler.newCompilation (C:\Users\DELL\Documents\Coding\office-js-api\Excel-Custom-Functions-master\node_modules\webpack\lib\Compiler.js:1044:26)
    at C:\Users\DELL\Documents\Coding\office-js-api\Excel-Custom-Functions-master\node_modules\webpack\lib\Compiler.js:1088:29
    at eval (eval at create (C:\Users\DELL\Documents\Coding\office-js-api\Excel-Custom-Functions-master\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:13:1)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

[process exited with code 1]
```

I was able to follow along on the Taskpane and React examples, just can't get this one to work for w/e reason. I didn't change the package.json or webpack at all.
Thank you.

**Comment by BrendyRyan** [comment]
Closing as this is a duplicate of [#455](https://github.com/OfficeDev/Office-Addin-Scripts/issues/455).

**Comment by BrendyRyan** [comment]
The issue ended up being I was using **Powershell**.
Ran the example using **CMD** and it worked.
